import "./globals.css";
import {
  Inter,
  Harmattan,
  Noto_Nastaliq_Urdu,
  Vazirmatn,
} from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const harmattan = Harmattan({ weight: "400", subsets: ["arabic"] });
const Nas = Noto_Nastaliq_Urdu({ weight: "400", subsets: ["arabic"] });
const Vazir = Vazirmatn({ weight: "400", subsets: ["arabic"] });
export const metadata = {
  title: "Nextjs Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Vazir.className}>{children}</body>
    </html>
  );
}
